remote_theme: "mmistakes/minimal-mistakes@4.24.0"
markdown: kramdown
title: Mathematik Glossar
minimal_mistakes_skin: default
search: true
search_full_content: true
locale: "de-DE"
title_separator: "|"
url: "https://glossar.thon.app/vmgkglossar"
baseurl: "/vmgkglossar"

include:
  - _pages

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp

search_provider: lunr
timezone: Europe/Berlin

lunr:
  search_within_pages: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

defaults:
  # _algebra
  - scope:
      path: ""
      type: algebra
    values:
      layout: single
      toc: true
  # _analysis
  - scope:
      path: ""
      type: analysis
    values:
      layout: single
      toc: true
  # _allgemein
  - scope:
      path: ""
      type: allgemein
    values:
      layout: single
      toc: true

collections:
  algebra:
    output: true
    permalink: /:collection/:path/
  analysis:
    output: true
    permalink: /:collection/:path/
  allgemein:
    output: true
    permalink: /:collection/:path/
